services:
  web:
    build: .
    network_mode: host
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
  #    - /usr/local/docker/redis/data:/data //文件映射




  db:
    image: mysql:5.7.23
    container_name: mysql
    network_mode: host
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
#    volumes:
#      - /home/mysql/data:/var/lib/mysql
#      - /home/mysql/conf/my.cnf:/etc/my.cnf:ro
#      - /home/mysql/init:/docker-entrypoint-initdb.d/

    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=F98YWrAU
      - MYSQL_DATABASE=data