services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: mysql:5.7.23
    ports:
      - 3306:3306
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /home/mysql/data:/var/lib/mysql
      - /home/mysql/conf/my.cnf:/etc/my.cnf:ro
      - /home/mysql/init:/docker-entrypoint-initdb.d/

    environment:
      - MYSQL_ROOT_PASSWORD=F98YWrAU